Repository SOEN-341-Project/Group-P-soen341project2022, pull requests merged in 2022-02, with the labels that each got.

#29 initialized backend with prisma ORM
  online-shopping-website/backend/.gitignore
  online-shopping-website/backend/package-lock.json
  online-shopping-website/backend/package.json
  online-shopping-website/backend/prisma/schema.prisma
  online-shopping-website/backend/tsconfig.json
Labels: backend, Feature

#25 feature/sidenav-for-product-filtering -- appearance
  online-shopping-website/.idea/misc.xml
  online-shopping-website/.idea/runConfigurations.xml
  online-shopping-website/.idea/vcs.xml
  online-shopping-website/.idea/workspace.xml
  online-shopping-website/package-lock.json
  online-shopping-website/package.json
  online-shopping-website/src/App.css
  online-shopping-website/src/App.js
  online-shopping-website/src/App.test.js
  online-shopping-website/src/Components/ProductGrid.js
  online-shopping-website/src/Components/SideNav.js
  online-shopping-website/src/TestValues.json
Labels: frontend, Feature, Epic 4 - Customer

#33 Added SideNav product filtering
  online-shopping-website/src/App.css
  online-shopping-website/src/App.js
  online-shopping-website/src/Components/ProductGrid.js
  online-shopping-website/src/Components/ProductPage.js
  online-shopping-website/src/Components/SideNav.js
  online-shopping-website/src/index.css
  online-shopping-website/src/index.js
Labels: frontend, User Story, Epic 4 - Customer

#41 Feature/create database
  online-shopping-website/backend/package-lock.json
  online-shopping-website/backend/package.json
  online-shopping-website/backend/prisma/migrations/20220209153534_dev_1/migration.sql
  online-shopping-website/backend/prisma/migrations/migration_lock.toml
  online-shopping-website/backend/prisma/schema.prisma
  online-shopping-website/backend/src/index.ts
  online-shopping-website/backend/ts-built/index.js
  online-shopping-website/backend/tsconfig.json
Labels: backend, Epic 1 - Login/Sign up, Epic 2 - Seller, Epic 3 - Admin, Epic 4 - Customer

#53 feature/routing
  online-shopping-website/.idea/workspace.xml
  online-shopping-website/package-lock.json
  online-shopping-website/package.json
  online-shopping-website/src/App.js
  online-shopping-website/src/Components/ProductGrid.js
Labels: frontend, User Story, Epic 4 - Customer

#49 feature/products-view-more-page
  online-shopping-website/.idea/inspectionProfiles/Project_Default.xml
  online-shopping-website/.idea/jsLinters/eslint.xml
  online-shopping-website/.idea/workspace.xml
  online-shopping-website/package-lock.json
  online-shopping-website/package.json
  online-shopping-website/src/App.css
  online-shopping-website/src/App.js
  online-shopping-website/src/Components/ProductDetails.js
  online-shopping-website/src/Components/ProductGrid.js
  online-shopping-website/src/Components/SideNav.js
Labels: frontend, User Story, Epic 4 - Customer

#54 feature/picture-uploads
  online-shopping-website/backend/.gitignore
  online-shopping-website/backend/package-lock.json
  online-shopping-website/backend/package.json
  online-shopping-website/backend/src/helpers/storage.ts
  online-shopping-website/backend/src/helpers/uploadFile.ts
  online-shopping-website/backend/src/index.ts
  online-shopping-website/backend/src/prismaFunctions.ts
  online-shopping-website/backend/src/test.html
Labels: backend, Epic 2 - Seller

#64 Feature/product-details-refactoring
  online-shopping-website/.idea/workspace.xml
  online-shopping-website/src/App.js
  online-shopping-website/src/Components/ProductDetails.js
  online-shopping-website/src/Components/ProductGrid.js
Labels: frontend, Epic 4 - Customer, Refactoring

#52 Added website branding
  online-shopping-website/public/BobbleBB.png
  online-shopping-website/public/favicon.ico
  online-shopping-website/public/index.html
  online-shopping-website/public/logo192.png
  online-shopping-website/public/logo512.png
  online-shopping-website/public/manifest.json
Labels: frontend

#62 Added Search Bar to SideNav
  online-shopping-website/src/App.js
  online-shopping-website/src/Components/ProductPage.js
  online-shopping-website/src/Components/SideNav.js
Labels: frontend, Epic 4 - Customer

#65 Hotfix: Removed unused routes from App routes
  online-shopping-website/src/App.js
Labels: bug, frontend

#63 feature/user routes
  online-shopping-website/backend/.gcloudignore
  online-shopping-website/backend/.gitignore
  online-shopping-website/backend/package-lock.json
  online-shopping-website/backend/package.json
  online-shopping-website/backend/prisma/migrations/20220218050228_address1_optional/migration.sql
  online-shopping-website/backend/prisma/schema.prisma
  online-shopping-website/backend/src/index.ts
  online-shopping-website/backend/src/prismaFunctions.ts
  online-shopping-website/backend/ts-built/index.js
Labels: backend, Epic 1 - Login/Sign up

#66 routing hot-fix (App.js)
  online-shopping-website/src/App.js
Labels: bug, frontend, Epic 4 - Customer

#68 address 1 is now required to make a user
  online-shopping-website/backend/prisma/migrations/20220221204754_address1_required/migration.sql
  online-shopping-website/backend/prisma/schema.prisma
  online-shopping-website/backend/src/index.ts
  online-shopping-website/backend/src/prismaFunctions.ts
Labels: bug, backend, Refactoring

#58 feature/seller-products-page
  online-shopping-website/.idea/workspace.xml
  online-shopping-website/.vscode/launch.json
  online-shopping-website/package-lock.json
  online-shopping-website/package.json
  online-shopping-website/src/App.css
  online-shopping-website/src/App.js
  online-shopping-website/src/Components/ProductDetails.js
  online-shopping-website/src/Components/Seller/SellerProductsForm.js
  online-shopping-website/src/Components/Seller/SellerProductsPage.js
  online-shopping-website/src/TestValues.json
Labels: frontend, User Story, Epic 2 - Seller

#45 Navbar Component
  online-shopping-website/.idea/workspace.xml
  online-shopping-website/src/App.css
  online-shopping-website/src/App.js
  online-shopping-website/src/Components/NavBar.js
  online-shopping-website/src/Components/ProductPage.js
  online-shopping-website/src/Components/SideNav.js
  online-shopping-website/src/icons/BOBBLE-02.png
  online-shopping-website/src/icons/BOBBLE-03.png
  online-shopping-website/src/icons/BOBBLE-04.png
  online-shopping-website/src/icons/BOBBLE-05.png
  online-shopping-website/src/icons/BOBBLE-06.png
  online-shopping-website/src/icons/BOBBLE-07.png
  online-shopping-website/src/icons/BOBBLE-08.png
  online-shopping-website/src/icons/BOBBLE-09.png
  online-shopping-website/src/icons/BOBBLE-10.png
Labels: frontend, User Story, Epic 4 - Customer

#69 test-endpoint made
  online-shopping-website/backend/package-lock.json
  online-shopping-website/backend/src/index.ts
Labels: backend, Refactoring

#67 feature/register-component
  online-shopping-website/.idea/workspace.xml
  online-shopping-website/src/App.css
  online-shopping-website/src/App.js
  online-shopping-website/src/Components/RegisterPage.js
Labels: frontend, Epic 1 - Login/Sign up

#70 Update README.md
  README.md
Labels: documentation

#72 Moved front-end application to frontend folder for CI deployment
  online-shopping-website/.gitignore
  online-shopping-website/frontend/package-lock.json
  online-shopping-website/frontend/package.json
  online-shopping-website/frontend/public/BobbleBB.png
  online-shopping-website/frontend/public/favicon.ico
  online-shopping-website/frontend/public/index.html
  online-shopping-website/frontend/public/manifest.json
  online-shopping-website/frontend/public/robots.txt
  online-shopping-website/frontend/src/App.css
  online-shopping-website/frontend/src/App.js
  online-shopping-website/frontend/src/App.test.js
  online-shopping-website/frontend/src/Components/NavBar.js
  online-shopping-website/frontend/src/Components/ProductDetails.js
  online-shopping-website/frontend/src/Components/ProductGrid.js
  online-shopping-website/frontend/src/Components/ProductPage.js
  online-shopping-website/frontend/src/Components/RegisterPage.js
  online-shopping-website/frontend/src/Components/SearchBar.js
  online-shopping-website/frontend/src/Components/Seller/SellerProductsForm.js
  online-shopping-website/frontend/src/Components/Seller/SellerProductsPage.js
  online-shopping-website/frontend/src/Components/SideNav.js
  online-shopping-website/frontend/src/TestValues.json
  online-shopping-website/frontend/src/fonts/CHANEY-Regular.otf
  online-shopping-website/frontend/src/icons/BOBBLE-02.png
  online-shopping-website/frontend/src/icons/BOBBLE-03.png
  online-shopping-website/frontend/src/icons/BOBBLE-04.png
  online-shopping-website/frontend/src/icons/BOBBLE-05.png
  online-shopping-website/frontend/src/icons/BOBBLE-06.png
  online-shopping-website/frontend/src/icons/BOBBLE-07.png
  online-shopping-website/frontend/src/icons/BOBBLE-08.png
  online-shopping-website/frontend/src/icons/BOBBLE-09.png
  online-shopping-website/frontend/src/icons/BOBBLE-10.png
  online-shopping-website/frontend/src/index.css
  online-shopping-website/frontend/src/index.js
  online-shopping-website/frontend/src/reportWebVitals.js
Labels: frontend
