Repository SOEN-341-Project/Group-P-soen341project2022, pull requests merged in 2022-01, with the labels that each got.

#2 Update README.md
  README.md
Labels: documentation

#7 Added date header to meeting minutes
  Meeting Minutes/P_Sprint1_1_January152022.md
Labels: documentation

#9 Update README.md
  README.md
Labels: documentation

#19 Prepared React app, added MUI, added heading font support
  Meeting Minutes/P_Sprint1_1_January152022.md
  Sprint 1/P_Sprint1_1_January152022.docx
  online-shopping-website/README.md
  online-shopping-website/package-lock.json
  online-shopping-website/package.json
  online-shopping-website/public/index.html
  online-shopping-website/src/App.css
  online-shopping-website/src/App.js
  online-shopping-website/src/App.test.js
  online-shopping-website/src/fonts/CHANEY-Regular.otf
  online-shopping-website/src/index.css
  online-shopping-website/src/index.js
  online-shopping-website/src/logo.svg
  online-shopping-website/src/setupTests.js
Labels: frontend

#22 Jungsoolee1 patch 1
  README.md
Labels: documentation

#21 Created responsive product grid using test data
  online-shopping-website/src/App.css
  online-shopping-website/src/App.js
  online-shopping-website/src/App.test.js
  online-shopping-website/src/Components/ProductGrid.js
  online-shopping-website/src/TestProducts.json
  online-shopping-website/src/index.css
Labels: frontend, Feature, Epic 4 - Customer

#26 removing malfunctioning markdown in PR template
  .github/pull_request_template.md
Labels: documentation
